-- SQLINES DEMO *** orward Engineering

/* SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; */
/* SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; */
/* SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'; */

-- SQLINES DEMO *** ------------------------------------
-- Schema DBCONTROL
-- SQLINES DEMO *** ------------------------------------

-- SQLINES DEMO *** ------------------------------------
-- Schema DBCONTROL
-- SQLINES DEMO *** ------------------------------------
--DROP DATABASE DBCONTROL;
CREATE DATABASE DBCONTROL;
USE [DBCONTROL] ;

-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** .`CLASIFICACION`
-- SQLINES DEMO *** ------------------------------------
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE CLASIFICACION (
  [ID_CLASIFICACION] INT NOT NULL IDENTITY,
  [DESCRIPCION] VARCHAR(4) NULL,
  PRIMARY KEY ([ID_CLASIFICACION]))
;


-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** .`PROVEEDOR`
-- SQLINES DEMO *** ------------------------------------
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE PROVEEDOR (
  [ID_PROVEEDOR] INT NOT NULL IDENTITY,
  [DESCRIPCION] VARCHAR(60) NOT NULL,
  [NIT] VARCHAR(15) NOT NULL,
  [PLAZO] INT NOT NULL,
  [ID_CLASIFICACION] INT NOT NULL,
  PRIMARY KEY ([ID_PROVEEDOR], [ID_CLASIFICACION]),
  CONSTRAINT [fk_PROVEEDOR_CLASIFICACION1]
    FOREIGN KEY ([ID_CLASIFICACION])
    REFERENCES CLASIFICACION ([ID_CLASIFICACION]));


-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** .`LIMITE`
-- SQLINES DEMO *** ------------------------------------
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE LIMITE (
  [ID_LIMITE] INT NOT NULL IDENTITY,
  [FECHA_LIMITE] DATE NULL,
  PRIMARY KEY ([ID_LIMITE]))
;


-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** .`ESTADO`
-- SQLINES DEMO *** ------------------------------------
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE ESTADO (
  [ID_ESTADO] INT NOT NULL IDENTITY,
  [DESCRIPCION] VARCHAR(45) NULL,
  PRIMARY KEY ([ID_ESTADO]))
;


-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** .`MOVIMIENTO`
-- SQLINES DEMO *** ------------------------------------
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE MOVIMIENTO (
  [ID_MOVIMIENTO] INT NOT NULL IDENTITY,
  [DESCRIPCION] VARCHAR(45) NOT NULL,
  PRIMARY KEY ([ID_MOVIMIENTO]))
;


-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** .`OPERACION`
-- SQLINES DEMO *** ------------------------------------
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE OPERACION (
  [ID_OPERACION] INT NOT NULL IDENTITY,
  [MONTO] DECIMAL(5,4) NOT NULL,
  [FECHA_COMPRA] DATE NOT NULL,
  [FECHA_PAGO] DATE NOT NULL,
  [DIAS] INT NOT NULL,
  [REFERENCIA] VARCHAR(45) NOT NULL,
  [MEDIO_PAGO] VARCHAR(45) NOT NULL,
  [NUM_DOCUMENTO] VARCHAR(45) NOT NULL,
  [TOKEN] VARCHAR(45) NOT NULL,
  [IMPUESTO_IVA] INT NULL,
  [IMPUESTO_ISR] INT NULL,
  [ID_ESTADO] INT NOT NULL,
  [ID_MOVIMIENTO] INT NOT NULL,
  [ID_PROVEEDOR] INT NOT NULL,
  [ID_CLASIFICACION] INT NULL,
  PRIMARY KEY ([ID_OPERACION], [ID_ESTADO], [ID_MOVIMIENTO], [ID_PROVEEDOR]),
  CONSTRAINT [fk_MONITOR_ESTADO1]
    FOREIGN KEY ([ID_ESTADO])
    REFERENCES ESTADO ([ID_ESTADO])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [fk_MONITOR_MOVIMIENTO1]
    FOREIGN KEY ([ID_MOVIMIENTO])
    REFERENCES MOVIMIENTO ([ID_MOVIMIENTO]),
  CONSTRAINT [fk_OPERACION_PROVEEDOR1]
    FOREIGN KEY ([ID_PROVEEDOR] , [ID_CLASIFICACION])
    REFERENCES PROVEEDOR ([ID_PROVEEDOR] , [ID_CLASIFICACION]));


-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** .`CUENTA`
-- SQLINES DEMO *** ------------------------------------
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE CUENTA (
  [ID_CUENTA] INT NOT NULL IDENTITY,
  [SALDO] DECIMAL(5,4) NULL,
  [NOMBRE_EMPRESA] VARCHAR(45) NULL,
  [DIRECCION] VARCHAR(45) NULL,
  [TELEFONO] VARCHAR(45) NULL,
  PRIMARY KEY ([ID_CUENTA]))
;


-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** .`BITACORA`
-- SQLINES DEMO *** ------------------------------------
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE BITACORA (
  [ID_BITACORA] INT NOT NULL IDENTITY,
  [NOMBRE_TABLA] VARCHAR(45) NOT NULL,
  [TIPO_MOV] VARCHAR(45) NULL,
  [USUARIO] VARCHAR(45) NULL,
  [FECHA_MOV] DATETIME NULL,
  [DESCRIPCION] VARCHAR(250) NULL,
  PRIMARY KEY ([ID_BITACORA]))
;


-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** .`RESUMEN`
-- SQLINES DEMO *** ------------------------------------
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE RESUMEN (
  [ID_RESUMEN] INT NOT NULL IDENTITY,
  [SALDO] DECIMAL(10,0) NULL,
  [ID_PROVEEDOR] INT NOT NULL,
  [ID_CLASIFICACION] INT NULL,
  PRIMARY KEY ([ID_RESUMEN], [ID_PROVEEDOR]),
  CONSTRAINT [fk_RESUMEN_PROVEEDOR1]
    FOREIGN KEY ([ID_PROVEEDOR] , [ID_CLASIFICACION])
    REFERENCES PROVEEDOR ([ID_PROVEEDOR] , [ID_CLASIFICACION]));


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */
